me5413_world:
  # the frame of all the poses below
  frame_id: 'world'

  # robot starting point
  start:
    x: 0.0
    y: 0.0
    yaw: 0.0

  # assembly line poses
  assembly_line_1:
    x: 4.0
    y: -1.7
    yaw: -1.57
  assembly_line_2:
    x: 4.0
    y: -4.7
    yaw: -1.57



  # delivery vehicle poses
  vehicle_1:
    x: 15.5
    y: -8.2
    yaw: -1.57
  vehicle_2:
    x: 2.9
    y: -9.9
    yaw: 0.0
  vehicle_3:
    x: 2.9
    y: -13.1
    yaw: 0.0

  vehicle_4:
    x: 8.0
    y: 1
    yaw: -0.785
  vehicle_5:
    x: 8.0
    y: -6.25
    yaw: 0.785

    
  
  
  vehicle_6:
    x: 13.0
    y: -6.25
    yaw: 2.356
  vehicle_7:
    x: 16.0
    y: 1
    yaw: -2.356
  vehicle_8:
    x: 12.0
    y: -3
    yaw: -1.57
  start_1:
    x: 13.0
    y: 1.6
    yaw: -0.525
